spring.application.name=backend
server.port=8080

spring.config.import=optional:configtree:/run/secrets/

spring.datasource.url=jdbc:postgresql://postgres:5432/mydb
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.cors.allowed-origins=http://localhost:5173
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type
app.cors.allow-credentials=true

app.cookie.refresh.secure=false
app.cookie.refresh.same-site=Strict

app.alg.timeout-ms=60000
app.alg.plateau-ms=10000
app.alg.should-optimize=true